# Generated by Django 4.2.2 on 2023-06-10 16:20

import contest_arena.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0012_alter_participant_max_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniHackermanQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentStudentHackerQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="HackerManImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=contest_arena.models.get_hackerman_image_upload_path
                    ),
                ),
                ("test_link", models.URLField(blank=True, null=True)),
                (
                    "image_for",
                    models.IntegerField(
                        default=0, help_text="All = 0, Alum = 1, Student = 2"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=contest_arena.models.get_meme_image_upload_path
                    ),
                ),
                (
                    "sound",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=contest_arena.models.get_meme_sound_upload_path,
                    ),
                ),
                ("text", models.TextField(blank=True, default=None, null=True)),
                (
                    "meme_for",
                    models.IntegerField(
                        default=0, help_text="All = 0, Alum = 1, Student = 2"
                    ),
                ),
                (
                    "meme_type",
                    models.IntegerField(
                        default=-1, help_text="Fail = 0 & Success = 1 & Wait = 2"
                    ),
                ),
                ("test_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(null=True)),
                ("info", models.CharField(blank=True, max_length=300, null=True)),
                ("info_link", models.URLField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.FileField(
                        null=True, upload_to=contest_arena.models.get_puzzle_upload_path
                    ),
                ),
                ("ans", models.CharField(max_length=50)),
                ("visible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Puzzle",
            },
        ),
        migrations.CreateModel(
            name="PuzzleForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans", models.TextField()),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.participant",
                    ),
                ),
                (
                    "puzzle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest_arena.puzzle",
                    ),
                ),
            ],
        ),
    ]
