# Generated by Django 4.2.2 on 2023-06-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest_arena", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackermanimage",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meme",
            name="sound",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
